{{ if .Values.clusteragent.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Values.namespace }}
  name: clusteragent
  labels:
    app: clusteragent
spec:
  serviceName: clusteragent
  replicas: 1
  selector:
    matchLabels:
      app: clusteragent
  template:
    metadata:
      labels:
        app: clusteragent
        hi_common_version: {{ default "" .Values.common_version | quote }}
    spec:
      restartPolicy: Always
      containers:
      - name: clusteragent
        {{- include "agent_image" . | indent 8 }}
        env:
        - name: HI_APP
          value: hiclusteragent
        - name: HI_AGENT_MODE
          value: "clusteragent"
        {{- include "agent_common_env" . | nindent 8 }}

        {{- if .Values.clusteragent.envs }}
        {{- toYaml .Values.clusteragent.envs | nindent 8 }}
        {{- end }}

        {{- include "agent_probe" . | indent 8 }}

        {{/* clusteragent resources */}}
        resources: {{- toYaml .Values.clusteragent.resources | nindent 10 }}

        volumeMounts:
        - mountPath: /usr/local/holoinsight/agent/agent.yaml
          name: holoinsight-agent-cm
          subPath: clusteragent_agent.yaml
      volumes:
      - name: holoinsight-agent-cm
        configMap:
          name: holoinsight-agent-cm
          defaultMode: 0644

{{- end }}
