---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: holoinsight-agent-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: holoinsight-agent-clusterrole
  apiGroup: rbac.authorization.k8s.io
