---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  # 这个 binding 的名字
  name: holoinsight-agent-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: holoinsight-agent-clusterrole
  apiGroup: rbac.authorization.k8s.io
