apiVersion: v1
kind: ConfigMap
metadata:
  name: holoinsight-agent-cm
  namespace: {{ .Values.namespace }}
data:
  registryAddr: {{ .Values.server.registry.addr }}
  gatewayAddr: {{ .Values.server.gateway.addr }}
  grpcSecure: {{ .Values.server.secure | quote }}
  workspace: {{ .Values.workspace | quote }}
  cluster: {{ .Values.cluster | quote }}
  daemonagent_agent.yaml: {{- default "" .Values.daemonagent.config | toYaml | indent 4 }}
  clusteragent_agent.yaml: {{- default "" .Values.clusteragent.config | toYaml | indent 4 }}
  centralagent_agent.yaml: {{- default "" .Values.centralagent.config | toYaml | indent 4 }}
