apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonagent
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: daemonagent
  minReadySeconds: {{ default 10 .Values.daemonagent.minReadySeconds }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: daemonagent
        app.kubernetes.io/name: daemonagent
        {{- include "chart_common_labels" . | indent 8 }}
        hi_common_version: {{ default "" .Values.common_version | quote }}
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        hostPath:
          path: /usr/local/holoinsight/agent/data
      - name: logs
        hostPath:
          path: /usr/local/holoinsight/agent/logs
      - name: hostfs
        hostPath:
          path: /
      - name: holoinsight-agent-cm
        configMap:
          name: holoinsight-agent-cm
          defaultMode: 0644
      hostPID: true
      hostNetwork: false
      containers:
      - name: daemonagent
        {{- include "agent_image" . | indent 8 }}
        securityContext:
          privileged: true
          procMount: Default
        env:
        - name: HI_APP
          value: daemonagent
        - name: HI_AGENT_MODE
          value: "daemonset"
        - name: HOSTFS
          value: "/hostfs"

        {{- include "agent_common_env" . | indent 8 }}

        {{/* daemonagent extra envs */}}
        {{- if .Values.daemonagent.envs }}
        {{- toYaml .Values.daemonagent.envs | nindent 8 }}
        {{- end }}

        {{- if hasKey .Values "agentK8sMetaSidecarCheck" }}
        - name: HI_K8S_META_SIDECAR_CHECK
          value: {{ .Values.agentK8sMetaSidecarCheck | quote }}
        {{- end }}

        {{- include "agent_probe" . | indent 8 }}

        volumeMounts:
        - mountPath: /hostfs
          name: hostfs
          mountPropagation: HostToContainer
        - mountPath: /usr/local/holoinsight/agent/data
          name: data
        - mountPath: /usr/local/holoinsight/agent/logs
          name: logs
        - mountPath: /usr/local/holoinsight/agent/agent.yaml
          name: holoinsight-agent-cm
          subPath: daemonagent_agent.yaml

        {{/* daemonagent resources */}}
        resources: {{- toYaml .Values.daemonagent.resources | nindent 10 }}
