apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: holoinsight-agent-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart_common_labels" . | indent 8 }}
stringData:
  apikey: {{ required "apikey is required" .Values.apikey }}
